### PR TITLE
* (bluefox) IMPORTANT: Node.js 16.x is now required at a minimum

### PR DESCRIPTION
**Pull request by GermanBluefox**
* (bluefox) replaced module `require` with `axios`
* (ChristianFue) Added support for Hmip-RGBW

### CODE REVIEW

**Comment by GermanBluefox** [comment]
@Apollon77 This PR still must be checked... :(

**Comment by Apollon77** [comment]
@mcm1957 I can not check that right now ... The main changes are in the "Linking of hmip" systems and I only have a HMIP production system. SO I can only assume @GermanBluefox  checked it. We could release as new minor version and see whats the feedback of community

**Comment by mcm1957** [comment]
Ok, then I would suggest to release to different minor versions - one for Bluefox Changes and one for the changes incorporated by PR #490. Would be easier to diffenence if any problem is detected.

**Comment by mcm1957** [comment]
@GermanBluefox Please rebase

**Comment by Apollon77** [comment]
I will merge now before we get more conflicts...still needs to be tested before release!

**Comment by mcm1957** [comment]
> I will merge now before we get more conflicts...still needs to be tested before release!

New release 1.22.0 has been released

**Pull request merged**
