### PR TITLE
Implement ENERGY_SENSORS_INTERFACE_CHANNEL

### PR DESCRIPTION
**Pull request by ApolloSK**

### CODE REVIEW

**Comment by Apollon77** [comment]
@ApolloSK Closed because?

**Comment by ApolloSK** [comment]
Because there is always a PullRequest with the same content
https://github.com/iobroker-community-adapters/ioBroker.hmip/pull/490#commits-pushed-3d8cfb0

**Comment by Apollon77** [comment]
ahh .. hehe ... yes missed, sorry. Will merge soon

**Comment by ApolloSK** [comment]
Yes, please merge it soon! Thanks!

**Pull request closed without merging**
